# version: '3.8'

services:
  app:
    build:
      args:
        user: ${VPS_USER}
        uid: ${VPS_UID}
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    user: ${VPS_USER}
    volumes:
      - pinkary-app:/var/www
      - ./database/database.sqlite:/var/www/database/database.sqlite
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - pinkary-app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  
volumes: 
  pinkary-app:
    driver: local
